# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6729b9c461adcb4d1087ac71b09c115b03eb98ace483d8830df55c4516213814a2fd1e9f9a27fc50f5f1fe991e273b843cff0d1e0d8e0c7235e7f2bcd562171e

test:
  secret_key_base: 5dc41750ee8b35fa1dd48912e155bb6768df1fb7485921f42aac5363c4bbf3f9d07a114e0e9f44b93996143e1c400b5b0be6a2ecf47875a6de7bf978aa65e564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
